export const Colors = {
  primary: '#3D6DFE',
  secondary: '#323232',
  lightGray: '#f2f2f2',
  gray: '#d3d3d3',
  darkGray: '#0b0b0b',
  black: '#000000',
  white: '#ffffff',
  whiteTransparent: '#ffffffcf',
  purple: '#7D4CDB',
  green: '#19be72',
  red: '#d50000',
  orange: '#ff5524',
  yellow: '#E1CD17',
  rippleColor: '#c4c4c4',
  BlackRGB10: 'rgba(0,0,0,0.1)',
  orangeRGBA0: 'rgba(255,85,36,0)',
  WhiteRGBA75: 'rgba(255,255,255,0.75)',
  WhiteRGBA50: 'rgba(255,255,255,0.50)',
  WhiteRGBA32: 'rgba(255,255,255,0.32)',
  WhiteRGBA15: 'rgba(255,255,255,0.15)',
};

export const FontFamily = {
  sofia_Black: 'SofiaSansCondensed-Black',
  sofia_BlackItalic: 'SofiaSansCondensed-BlackItalic',
  sofia_Bold: 'SofiaSansCondensed-Bold',
  sofia_BoldItalic: 'SofiaSansCondensed-BoldItalic',
  sofia_ExtraBold: 'SofiaSansCondensed-ExtraBold',
  sofia_ExtraBoldItalic: 'SofiaSansCondensed-ExtraBoldItalic',
  sofia_ExtraLight: 'SofiaSansCondensed-ExtraLight',
  sofia_ExtraLightItalic: 'SofiaSansCondensed-',
  sofia_Italic: 'SofiaSansCondensed-Italic',
  sofia_Light: 'SofiaSansCondensed-Light',
  sofia_LightItalic: 'SofiaSansCondensed-LightItalic',
  sofia_Medium: 'SofiaSansCondensed-Medium',
  sofia_MediumItalic: 'SofiaSansCondensed-MediumItalic',
  sofia_Regular: 'SofiaSansCondensed-Regular',
  sofia_SemiBold: 'SofiaSansCondensed-SemiBold',
  sofia_SemiBoldItalic: 'SofiaSansCondensed-SemiBoldItalic',
  sofia_Thin: 'SofiaSansCondensed-Thin',
  sofia_ThinItalic: 'SofiaSansCondensed-ThinItalic',
};
